### ISSUE TITLE
Build failure on aarch64

### ISSUE THREAD

**Issue by dicta** [conda-forge/log4cpp-feedstock#5]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Package fails to build on aarch64 (invoking conda-build directly).

Failure occurs during the `./configure` step of build.sh due to not understanding the host `aarch64-conda-linux-gnu`. I believe this is caused by a very old config.sub and config.guess being present that does not handle this architecture. This seems to be another variant of the issue that is present for many autotools packages with macos-arm64.

Related:
- https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
- https://github.com/conda/conda-build/issues/4123

Following the format of the above blog post, the following change appears to fix the issue on my system:

```
diff --git a/recipe/build.sh b/recipe/build.sh
index 2e4237e..576692f 100644
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Get an updated config.sub and config.guess
+cp $BUILD_PREFIX/share/gnuconfig/config.* config/
+
 ./configure --prefix="${PREFIX}" \
             --host="${HOST}" \
             --build="${BUILD}"
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index b616d8d..824da7f 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -25,6 +25,7 @@ requirements:
     - {{ compiler('cxx') }}
     - make  # [unix]
     - autoconf  # [unix]
+    - gnuconfig # [unix]
     - cmake  # [win]
     - ninja  # [win]
```

**Comment by ryanvolz** [comment]
Thanks for doing some investigation. I take this to mean that you are interested in having `log4cpp` compiled for `osx-arm64` here on conda-forge? So far it has not been scheduled for that migration, but it certainly could be if there is interest. I'd suggest putting in a pull request to `conda-forge-pinning` to get `log4cpp` added to the macOS arm64 migration list, something like https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1451. Then a pull request will be automatically generated to migrate `log4cpp`, and we can fix up the build script as you've indicated while getting the compiled packages as a bonus.

**Comment by dicta** [comment]
I'm actually primarily looking at the feasibility of a linux-aarch64 build for gnuradio (of which log4cpp is a dependency), being able to support macOS is just a bonus. Sorry if that was unclear!

**Comment by ryanvolz** [comment]
Well that's even better, since I'm the maintainer all the way up that chain! Still, a pull request like the one I linked, only for `gnuradio`, would be helpful. That'll set off a chain of things which would eventually result in getting that package built. I'll say now, though, that I know a holdup is going to be `qt` because that is notoriously hard to build and is already stuck on its migration for macOS arm64. If that's the only thing, then we could potentially get `gnuradio` but without `gnuradio-qtgui` for the time being.

**Comment by ryanvolz** [comment]
Merged in #7. The whole `gnuradio` chain is ongoing.

**Comment by ryanvolz** [comment]
FYI, the `gnuradio` packages now support `linux-aarch64`, `linux-ppc64le`, and `osx-arm64` (the last two minus `gnuradio-qtgui`). Additional gnuradio-related packages are still ongoing but making good progress.

**Comment by dicta** [comment]
Thanks for your help in getting this all integrated and regularly building. I've been following along as this worked its way up the chain and saw the merge in gnuradio-feedstock yesterday!
